name: local
values:
  - key: authToken
    value: ''
  - key: leagueCode
    value: ''
  - key: userId
    value: ''
  - key: leagueId
    value: ''
  - key: season
    value: ''
  - key: teamId
    value: ''
  - key: playerId
    value: ''
  - key: predictionId
    value: ''
