name: local
values:
  - key: authToken
    value: ''
  - key: leagueId
    value: ''
  - key: leagueCode
    value: ''
  - key: userId
    value: ''
  - key: league_id
    value: ''
  - key: season
    value: ''
  - key: team_id
    value: ''
  - key: playerId
    value: ''
