// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for FixtureStatus.
const (
	FixtureStatusFinished   FixtureStatus = "finished"
	FixtureStatusInProgress FixtureStatus = "in_progress"
	FixtureStatusUpcoming   FixtureStatus = "upcoming"
)

// Valid indicates whether the value is a known member of the FixtureStatus enum.
func (e FixtureStatus) Valid() bool {
	switch e {
	case FixtureStatusFinished:
		return true
	case FixtureStatusInProgress:
		return true
	case FixtureStatusUpcoming:
		return true
	default:
		return false
	}
}

// Defines values for FixtureWithMemberPredictionsStatus.
const (
	FixtureWithMemberPredictionsStatusFinished   FixtureWithMemberPredictionsStatus = "finished"
	FixtureWithMemberPredictionsStatusInProgress FixtureWithMemberPredictionsStatus = "in_progress"
	FixtureWithMemberPredictionsStatusUpcoming   FixtureWithMemberPredictionsStatus = "upcoming"
)

// Valid indicates whether the value is a known member of the FixtureWithMemberPredictionsStatus enum.
func (e FixtureWithMemberPredictionsStatus) Valid() bool {
	switch e {
	case FixtureWithMemberPredictionsStatusFinished:
		return true
	case FixtureWithMemberPredictionsStatusInProgress:
		return true
	case FixtureWithMemberPredictionsStatusUpcoming:
		return true
	default:
		return false
	}
}

// Defines values for FixtureWithPredictionStatus.
const (
	FixtureWithPredictionStatusFinished   FixtureWithPredictionStatus = "finished"
	FixtureWithPredictionStatusInProgress FixtureWithPredictionStatus = "in_progress"
	FixtureWithPredictionStatusUpcoming   FixtureWithPredictionStatus = "upcoming"
)

// Valid indicates whether the value is a known member of the FixtureWithPredictionStatus enum.
func (e FixtureWithPredictionStatus) Valid() bool {
	switch e {
	case FixtureWithPredictionStatusFinished:
		return true
	case FixtureWithPredictionStatusInProgress:
		return true
	case FixtureWithPredictionStatusUpcoming:
		return true
	default:
		return false
	}
}

// Defines values for LeagueMemberRole.
const (
	Member LeagueMemberRole = "member"
	Owner  LeagueMemberRole = "owner"
)

// Valid indicates whether the value is a known member of the LeagueMemberRole enum.
func (e LeagueMemberRole) Valid() bool {
	switch e {
	case Member:
		return true
	case Owner:
		return true
	default:
		return false
	}
}

// Defines values for PlayerHandicapCategory.
const (
	GroupTopScorer PlayerHandicapCategory = "group_top_scorer"
	TotalTopScorer PlayerHandicapCategory = "total_top_scorer"
)

// Valid indicates whether the value is a known member of the PlayerHandicapCategory enum.
func (e PlayerHandicapCategory) Valid() bool {
	switch e {
	case GroupTopScorer:
		return true
	case TotalTopScorer:
		return true
	default:
		return false
	}
}

// Defines values for TeamHandicapCategory.
const (
	GroupWinner  TeamHandicapCategory = "group_winner"
	Playoff      TeamHandicapCategory = "playoff"
	Semifinalist TeamHandicapCategory = "semifinalist"
	Winner       TeamHandicapCategory = "winner"
)

// Valid indicates whether the value is a known member of the TeamHandicapCategory enum.
func (e TeamHandicapCategory) Valid() bool {
	switch e {
	case GroupWinner:
		return true
	case Playoff:
		return true
	case Semifinalist:
		return true
	case Winner:
		return true
	default:
		return false
	}
}

// Defines values for TournamentStatus.
const (
	TournamentStatusConcluded  TournamentStatus = "concluded"
	TournamentStatusInProgress TournamentStatus = "in_progress"
	TournamentStatusUpcoming   TournamentStatus = "upcoming"
)

// Valid indicates whether the value is a known member of the TournamentStatus enum.
func (e TournamentStatus) Valid() bool {
	switch e {
	case TournamentStatusConcluded:
		return true
	case TournamentStatusInProgress:
		return true
	case TournamentStatusUpcoming:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	Active    UserStatus = "active"
	Suspended UserStatus = "suspended"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Suspended:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// Fixture defines model for Fixture.
type Fixture struct {
	AwayTeamId   openapi_types.UUID `json:"away_team_id"`
	ExternalId   int                `json:"external_id"`
	GoalsAway    *int               `json:"goals_away,omitempty"`
	GoalsHome    *int               `json:"goals_home,omitempty"`
	HomeTeamId   openapi_types.UUID `json:"home_team_id"`
	Id           openapi_types.UUID `json:"id"`
	KickoffAt    time.Time          `json:"kickoff_at"`
	Status       FixtureStatus      `json:"status"`
	TournamentId openapi_types.UUID `json:"tournament_id"`
}

// FixtureStatus defines model for Fixture.Status.
type FixtureStatus string

// FixtureListResponse defines model for FixtureListResponse.
type FixtureListResponse struct {
	Fixtures []FixtureWithPrediction `json:"fixtures"`
}

// FixtureWithMemberPredictions defines model for FixtureWithMemberPredictions.
type FixtureWithMemberPredictions struct {
	AwayTeamId   openapi_types.UUID                 `json:"away_team_id"`
	ExternalId   int                                `json:"external_id"`
	GoalsAway    *int                               `json:"goals_away,omitempty"`
	GoalsHome    *int                               `json:"goals_home,omitempty"`
	HomeTeamId   openapi_types.UUID                 `json:"home_team_id"`
	Id           openapi_types.UUID                 `json:"id"`
	KickoffAt    time.Time                          `json:"kickoff_at"`
	Predictions  []MemberPrediction                 `json:"predictions"`
	Status       FixtureWithMemberPredictionsStatus `json:"status"`
	TournamentId openapi_types.UUID                 `json:"tournament_id"`
}

// FixtureWithMemberPredictionsStatus defines model for FixtureWithMemberPredictions.Status.
type FixtureWithMemberPredictionsStatus string

// FixtureWithPrediction defines model for FixtureWithPrediction.
type FixtureWithPrediction struct {
	AwayTeamId   openapi_types.UUID          `json:"away_team_id"`
	ExternalId   int                         `json:"external_id"`
	GoalsAway    *int                        `json:"goals_away,omitempty"`
	GoalsHome    *int                        `json:"goals_home,omitempty"`
	HomeTeamId   openapi_types.UUID          `json:"home_team_id"`
	Id           openapi_types.UUID          `json:"id"`
	KickoffAt    time.Time                   `json:"kickoff_at"`
	Prediction   *ScorePrediction            `json:"prediction,omitempty"`
	Status       FixtureWithPredictionStatus `json:"status"`
	TournamentId openapi_types.UUID          `json:"tournament_id"`
}

// FixtureWithPredictionStatus defines model for FixtureWithPrediction.Status.
type FixtureWithPredictionStatus string

// League defines model for League.
type League struct {
	Code         string             `json:"code"`
	CreatedAt    time.Time          `json:"created_at"`
	Id           openapi_types.UUID `json:"id"`
	Name         string             `json:"name"`
	OwnerId      openapi_types.UUID `json:"owner_id"`
	TournamentId openapi_types.UUID `json:"tournament_id"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

// LeagueDetail defines model for LeagueDetail.
type LeagueDetail struct {
	Code         string             `json:"code"`
	CreatedAt    time.Time          `json:"created_at"`
	Id           openapi_types.UUID `json:"id"`
	Members      []LeagueMember     `json:"members"`
	Name         string             `json:"name"`
	OwnerId      openapi_types.UUID `json:"owner_id"`
	TournamentId openapi_types.UUID `json:"tournament_id"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

// LeagueListResponse defines model for LeagueListResponse.
type LeagueListResponse struct {
	Leagues []League `json:"leagues"`
}

// LeagueMember defines model for LeagueMember.
type LeagueMember struct {
	JoinedAt time.Time          `json:"joined_at"`
	Role     LeagueMemberRole   `json:"role"`
	UserId   openapi_types.UUID `json:"user_id"`
}

// LeagueMemberRole defines model for LeagueMember.Role.
type LeagueMemberRole string

// LeaguePredictionsResponse defines model for LeaguePredictionsResponse.
type LeaguePredictionsResponse struct {
	Fixtures []FixtureWithMemberPredictions `json:"fixtures"`
}

// MemberPrediction defines model for MemberPrediction.
type MemberPrediction struct {
	DisplayName string             `json:"display_name"`
	GoalsAway   *int               `json:"goals_away,omitempty"`
	GoalsHome   *int               `json:"goals_home,omitempty"`
	Points      *int               `json:"points,omitempty"`
	UserId      openapi_types.UUID `json:"user_id"`
}

// Player defines model for Player.
type Player struct {
	Handicaps map[string]int     `json:"handicaps"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	TeamLogo  string             `json:"team_logo"`
	TeamName  string             `json:"team_name"`
}

// PlayerHandicap defines model for PlayerHandicap.
type PlayerHandicap struct {
	Points int `json:"points"`
}

// PlayerHandicapCategory defines model for PlayerHandicapCategory.
type PlayerHandicapCategory string

// PlayerListResponse defines model for PlayerListResponse.
type PlayerListResponse struct {
	Players []Player `json:"players"`
}

// ScorePrediction defines model for ScorePrediction.
type ScorePrediction struct {
	CreatedAt time.Time          `json:"created_at"`
	FixtureId openapi_types.UUID `json:"fixture_id"`
	GoalsAway int                `json:"goals_away"`
	GoalsHome int                `json:"goals_home"`
	Id        openapi_types.UUID `json:"id"`
	Points    *int               `json:"points,omitempty"`
	UpdatedAt time.Time          `json:"updated_at"`
	UserId    openapi_types.UUID `json:"user_id"`
}

// TeamHandicap defines model for TeamHandicap.
type TeamHandicap struct {
	Points int `json:"points"`
}

// TeamHandicapCategory defines model for TeamHandicapCategory.
type TeamHandicapCategory string

// Tournament defines model for Tournament.
type Tournament struct {
	CreatedAt time.Time          `json:"created_at"`
	EndsAt    time.Time          `json:"ends_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	StartsAt  time.Time          `json:"starts_at"`
	Status    TournamentStatus   `json:"status"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// TournamentStatus defines model for Tournament.Status.
type TournamentStatus string

// TournamentListResponse defines model for TournamentListResponse.
type TournamentListResponse struct {
	Tournaments []Tournament `json:"tournaments"`
}

// User defines model for User.
type User struct {
	CreatedAt   time.Time           `json:"created_at"`
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	Status      UserStatus          `json:"status"`
	UpdatedAt   time.Time           `json:"updated_at"`
}

// UserStatus defines model for User.Status.
type UserStatus string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// CreateLeagueJSONBody defines parameters for CreateLeague.
type CreateLeagueJSONBody struct {
	Name         string             `json:"name"`
	TournamentId openapi_types.UUID `json:"tournament_id"`
}

// JoinLeagueJSONBody defines parameters for JoinLeague.
type JoinLeagueJSONBody struct {
	Code string `json:"code"`
}

// UpdateLeagueNameJSONBody defines parameters for UpdateLeagueName.
type UpdateLeagueNameJSONBody struct {
	Name string `json:"name"`
}

// UpsertScorePredictionJSONBody defines parameters for UpsertScorePrediction.
type UpsertScorePredictionJSONBody struct {
	GoalsAway int `json:"goals_away"`
	GoalsHome int `json:"goals_home"`
}

// CreateTournamentJSONBody defines parameters for CreateTournament.
type CreateTournamentJSONBody struct {
	EndsAt   time.Time `json:"ends_at"`
	Name     string    `json:"name"`
	Slug     string    `json:"slug"`
	StartsAt time.Time `json:"starts_at"`
}

// SearchPlayersParams defines parameters for SearchPlayers.
type SearchPlayersParams struct {
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// CreateLeagueJSONRequestBody defines body for CreateLeague for application/json ContentType.
type CreateLeagueJSONRequestBody CreateLeagueJSONBody

// JoinLeagueJSONRequestBody defines body for JoinLeague for application/json ContentType.
type JoinLeagueJSONRequestBody JoinLeagueJSONBody

// UpdateLeagueNameJSONRequestBody defines body for UpdateLeagueName for application/json ContentType.
type UpdateLeagueNameJSONRequestBody UpdateLeagueNameJSONBody

// UpsertScorePredictionJSONRequestBody defines body for UpsertScorePrediction for application/json ContentType.
type UpsertScorePredictionJSONRequestBody UpsertScorePredictionJSONBody

// CreateTournamentJSONRequestBody defines body for CreateTournament for application/json ContentType.
type CreateTournamentJSONRequestBody CreateTournamentJSONBody
