// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for LeagueMemberRole.
const (
	Member LeagueMemberRole = "member"
	Owner  LeagueMemberRole = "owner"
)

// Valid indicates whether the value is a known member of the LeagueMemberRole enum.
func (e LeagueMemberRole) Valid() bool {
	switch e {
	case Member:
		return true
	case Owner:
		return true
	default:
		return false
	}
}

// Defines values for PlayerHandicapCategory.
const (
	GroupTopScorer PlayerHandicapCategory = "group_top_scorer"
	TotalTopScorer PlayerHandicapCategory = "total_top_scorer"
)

// Valid indicates whether the value is a known member of the PlayerHandicapCategory enum.
func (e PlayerHandicapCategory) Valid() bool {
	switch e {
	case GroupTopScorer:
		return true
	case TotalTopScorer:
		return true
	default:
		return false
	}
}

// Defines values for TeamHandicapCategory.
const (
	GroupWinner  TeamHandicapCategory = "group_winner"
	Playoff      TeamHandicapCategory = "playoff"
	Semifinalist TeamHandicapCategory = "semifinalist"
	Winner       TeamHandicapCategory = "winner"
)

// Valid indicates whether the value is a known member of the TeamHandicapCategory enum.
func (e TeamHandicapCategory) Valid() bool {
	switch e {
	case GroupWinner:
		return true
	case Playoff:
		return true
	case Semifinalist:
		return true
	case Winner:
		return true
	default:
		return false
	}
}

// Defines values for TournamentStatus.
const (
	Concluded  TournamentStatus = "concluded"
	InProgress TournamentStatus = "in_progress"
	Upcoming   TournamentStatus = "upcoming"
)

// Valid indicates whether the value is a known member of the TournamentStatus enum.
func (e TournamentStatus) Valid() bool {
	switch e {
	case Concluded:
		return true
	case InProgress:
		return true
	case Upcoming:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	Active    UserStatus = "active"
	Suspended UserStatus = "suspended"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Suspended:
		return true
	default:
		return false
	}
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// League defines model for League.
type League struct {
	Code         string             `json:"code"`
	CreatedAt    time.Time          `json:"created_at"`
	Id           openapi_types.UUID `json:"id"`
	Name         string             `json:"name"`
	OwnerId      openapi_types.UUID `json:"owner_id"`
	TournamentId openapi_types.UUID `json:"tournament_id"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

// LeagueDetail defines model for LeagueDetail.
type LeagueDetail struct {
	Code         string             `json:"code"`
	CreatedAt    time.Time          `json:"created_at"`
	Id           openapi_types.UUID `json:"id"`
	Members      []LeagueMember     `json:"members"`
	Name         string             `json:"name"`
	OwnerId      openapi_types.UUID `json:"owner_id"`
	TournamentId openapi_types.UUID `json:"tournament_id"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

// LeagueListResponse defines model for LeagueListResponse.
type LeagueListResponse struct {
	Leagues []League `json:"leagues"`
}

// LeagueMember defines model for LeagueMember.
type LeagueMember struct {
	JoinedAt time.Time          `json:"joined_at"`
	Role     LeagueMemberRole   `json:"role"`
	UserId   openapi_types.UUID `json:"user_id"`
}

// LeagueMemberRole defines model for LeagueMember.Role.
type LeagueMemberRole string

// Player defines model for Player.
type Player struct {
	Handicaps map[string]int     `json:"handicaps"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	TeamLogo  string             `json:"team_logo"`
	TeamName  string             `json:"team_name"`
}

// PlayerHandicap defines model for PlayerHandicap.
type PlayerHandicap struct {
	Points int `json:"points"`
}

// PlayerHandicapCategory defines model for PlayerHandicapCategory.
type PlayerHandicapCategory string

// PlayerListResponse defines model for PlayerListResponse.
type PlayerListResponse struct {
	Players []Player `json:"players"`
}

// TeamHandicap defines model for TeamHandicap.
type TeamHandicap struct {
	Points int `json:"points"`
}

// TeamHandicapCategory defines model for TeamHandicapCategory.
type TeamHandicapCategory string

// Tournament defines model for Tournament.
type Tournament struct {
	CreatedAt time.Time          `json:"created_at"`
	EndsAt    time.Time          `json:"ends_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	StartsAt  time.Time          `json:"starts_at"`
	Status    TournamentStatus   `json:"status"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// TournamentStatus defines model for Tournament.Status.
type TournamentStatus string

// TournamentListResponse defines model for TournamentListResponse.
type TournamentListResponse struct {
	Tournaments []Tournament `json:"tournaments"`
}

// User defines model for User.
type User struct {
	CreatedAt   time.Time           `json:"created_at"`
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	Status      UserStatus          `json:"status"`
	UpdatedAt   time.Time           `json:"updated_at"`
}

// UserStatus defines model for User.Status.
type UserStatus string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// CreateLeagueJSONBody defines parameters for CreateLeague.
type CreateLeagueJSONBody struct {
	Name         string             `json:"name"`
	TournamentId openapi_types.UUID `json:"tournament_id"`
}

// JoinLeagueJSONBody defines parameters for JoinLeague.
type JoinLeagueJSONBody struct {
	Code string `json:"code"`
}

// UpdateLeagueNameJSONBody defines parameters for UpdateLeagueName.
type UpdateLeagueNameJSONBody struct {
	Name string `json:"name"`
}

// CreateTournamentJSONBody defines parameters for CreateTournament.
type CreateTournamentJSONBody struct {
	EndsAt   time.Time `json:"ends_at"`
	Name     string    `json:"name"`
	Slug     string    `json:"slug"`
	StartsAt time.Time `json:"starts_at"`
}

// SearchPlayersParams defines parameters for SearchPlayers.
type SearchPlayersParams struct {
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// CreateLeagueJSONRequestBody defines body for CreateLeague for application/json ContentType.
type CreateLeagueJSONRequestBody CreateLeagueJSONBody

// JoinLeagueJSONRequestBody defines body for JoinLeague for application/json ContentType.
type JoinLeagueJSONRequestBody JoinLeagueJSONBody

// UpdateLeagueNameJSONRequestBody defines body for UpdateLeagueName for application/json ContentType.
type UpdateLeagueNameJSONRequestBody UpdateLeagueNameJSONBody

// CreateTournamentJSONRequestBody defines body for CreateTournament for application/json ContentType.
type CreateTournamentJSONRequestBody CreateTournamentJSONBody
