// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for FixtureResponseStatus.
const (
	FixtureResponseStatusFinished   FixtureResponseStatus = "finished"
	FixtureResponseStatusInProgress FixtureResponseStatus = "in_progress"
	FixtureResponseStatusUpcoming   FixtureResponseStatus = "upcoming"
)

// Valid indicates whether the value is a known member of the FixtureResponseStatus enum.
func (e FixtureResponseStatus) Valid() bool {
	switch e {
	case FixtureResponseStatusFinished:
		return true
	case FixtureResponseStatusInProgress:
		return true
	case FixtureResponseStatusUpcoming:
		return true
	default:
		return false
	}
}

// Defines values for LeagueFixtureViewResponseStatus.
const (
	LeagueFixtureViewResponseStatusFinished   LeagueFixtureViewResponseStatus = "finished"
	LeagueFixtureViewResponseStatusInProgress LeagueFixtureViewResponseStatus = "in_progress"
	LeagueFixtureViewResponseStatusUpcoming   LeagueFixtureViewResponseStatus = "upcoming"
)

// Valid indicates whether the value is a known member of the LeagueFixtureViewResponseStatus enum.
func (e LeagueFixtureViewResponseStatus) Valid() bool {
	switch e {
	case LeagueFixtureViewResponseStatusFinished:
		return true
	case LeagueFixtureViewResponseStatusInProgress:
		return true
	case LeagueFixtureViewResponseStatusUpcoming:
		return true
	default:
		return false
	}
}

// Defines values for LeagueMemberRole.
const (
	Member LeagueMemberRole = "member"
	Owner  LeagueMemberRole = "owner"
)

// Valid indicates whether the value is a known member of the LeagueMemberRole enum.
func (e LeagueMemberRole) Valid() bool {
	switch e {
	case Member:
		return true
	case Owner:
		return true
	default:
		return false
	}
}

// Defines values for PlayerHandicapCategory.
const (
	GroupTopScorer PlayerHandicapCategory = "group_top_scorer"
	TotalTopScorer PlayerHandicapCategory = "total_top_scorer"
)

// Valid indicates whether the value is a known member of the PlayerHandicapCategory enum.
func (e PlayerHandicapCategory) Valid() bool {
	switch e {
	case GroupTopScorer:
		return true
	case TotalTopScorer:
		return true
	default:
		return false
	}
}

// Defines values for TeamHandicapCategory.
const (
	GroupWinner  TeamHandicapCategory = "group_winner"
	Playoff      TeamHandicapCategory = "playoff"
	Semifinalist TeamHandicapCategory = "semifinalist"
	Winner       TeamHandicapCategory = "winner"
)

// Valid indicates whether the value is a known member of the TeamHandicapCategory enum.
func (e TeamHandicapCategory) Valid() bool {
	switch e {
	case GroupWinner:
		return true
	case Playoff:
		return true
	case Semifinalist:
		return true
	case Winner:
		return true
	default:
		return false
	}
}

// Defines values for TournamentStatus.
const (
	TournamentStatusConcluded  TournamentStatus = "concluded"
	TournamentStatusInProgress TournamentStatus = "in_progress"
	TournamentStatusUpcoming   TournamentStatus = "upcoming"
)

// Valid indicates whether the value is a known member of the TournamentStatus enum.
func (e TournamentStatus) Valid() bool {
	switch e {
	case TournamentStatusConcluded:
		return true
	case TournamentStatusInProgress:
		return true
	case TournamentStatusUpcoming:
		return true
	default:
		return false
	}
}

// Defines values for UserStatus.
const (
	Active    UserStatus = "active"
	Suspended UserStatus = "suspended"
)

// Valid indicates whether the value is a known member of the UserStatus enum.
func (e UserStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Suspended:
		return true
	default:
		return false
	}
}

// Defines values for UserFixtureViewResponseStatus.
const (
	UserFixtureViewResponseStatusFinished   UserFixtureViewResponseStatus = "finished"
	UserFixtureViewResponseStatusInProgress UserFixtureViewResponseStatus = "in_progress"
	UserFixtureViewResponseStatusUpcoming   UserFixtureViewResponseStatus = "upcoming"
)

// Valid indicates whether the value is a known member of the UserFixtureViewResponseStatus enum.
func (e UserFixtureViewResponseStatus) Valid() bool {
	switch e {
	case UserFixtureViewResponseStatusFinished:
		return true
	case UserFixtureViewResponseStatusInProgress:
		return true
	case UserFixtureViewResponseStatusUpcoming:
		return true
	default:
		return false
	}
}

// BulkPlayerPredictionItem defines model for BulkPlayerPredictionItem.
type BulkPlayerPredictionItem struct {
	Category    PlayerHandicapCategory `json:"category"`
	GroupLetter *string                `json:"group_letter,omitempty"`

	// PlayerId null clears the slot
	PlayerId *openapi_types.UUID `json:"player_id,omitempty"`
}

// BulkTeamPredictionItem defines model for BulkTeamPredictionItem.
type BulkTeamPredictionItem struct {
	Category    TeamHandicapCategory `json:"category"`
	GroupLetter *string              `json:"group_letter,omitempty"`
	SlotIndex   int                  `json:"slot_index"`

	// TeamId null clears the slot
	TeamId *openapi_types.UUID `json:"team_id,omitempty"`
}

// BulkUpsertPlayerPredictionsRequest defines model for BulkUpsertPlayerPredictionsRequest.
type BulkUpsertPlayerPredictionsRequest = []BulkPlayerPredictionItem

// BulkUpsertTeamPredictionsRequest defines model for BulkUpsertTeamPredictionsRequest.
type BulkUpsertTeamPredictionsRequest = []BulkTeamPredictionItem

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// FixtureResponse defines model for FixtureResponse.
type FixtureResponse struct {
	AwayTeamName     string                `json:"away_team_name"`
	ExternalId       int                   `json:"external_id"`
	GoalsAway        *int                  `json:"goals_away,omitempty"`
	GoalsHome        *int                  `json:"goals_home,omitempty"`
	HomeTeamName     string                `json:"home_team_name"`
	Id               openapi_types.UUID    `json:"id"`
	KickoffAt        time.Time             `json:"kickoff_at"`
	PredictionLocked bool                  `json:"prediction_locked"`
	Round            string                `json:"round"`
	Status           FixtureResponseStatus `json:"status"`
	TournamentId     openapi_types.UUID    `json:"tournament_id"`
}

// FixtureResponseStatus defines model for FixtureResponse.Status.
type FixtureResponseStatus string

// League defines model for League.
type League struct {
	Code         string             `json:"code"`
	CreatedAt    time.Time          `json:"created_at"`
	Id           openapi_types.UUID `json:"id"`
	Name         string             `json:"name"`
	OwnerId      openapi_types.UUID `json:"owner_id"`
	TournamentId openapi_types.UUID `json:"tournament_id"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

// LeagueDetail defines model for LeagueDetail.
type LeagueDetail struct {
	Code         string             `json:"code"`
	CreatedAt    time.Time          `json:"created_at"`
	Id           openapi_types.UUID `json:"id"`
	Members      []LeagueMember     `json:"members"`
	Name         string             `json:"name"`
	OwnerId      openapi_types.UUID `json:"owner_id"`
	TournamentId openapi_types.UUID `json:"tournament_id"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

// LeagueFixtureViewResponse defines model for LeagueFixtureViewResponse.
type LeagueFixtureViewResponse struct {
	AwayTeamName     string                          `json:"away_team_name"`
	ExternalId       int                             `json:"external_id"`
	GoalsAway        *int                            `json:"goals_away,omitempty"`
	GoalsHome        *int                            `json:"goals_home,omitempty"`
	HomeTeamName     string                          `json:"home_team_name"`
	Id               openapi_types.UUID              `json:"id"`
	KickoffAt        time.Time                       `json:"kickoff_at"`
	PredictionLocked bool                            `json:"prediction_locked"`
	Predictions      []LeagueMemberScorePrediction   `json:"predictions"`
	Round            string                          `json:"round"`
	Status           LeagueFixtureViewResponseStatus `json:"status"`
	TournamentId     openapi_types.UUID              `json:"tournament_id"`
}

// LeagueFixtureViewResponseStatus defines model for LeagueFixtureViewResponse.Status.
type LeagueFixtureViewResponseStatus string

// LeagueListItem defines model for LeagueListItem.
type LeagueListItem struct {
	Code      string             `json:"code"`
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`

	// MemberCount Total number of members in this league.
	MemberCount  int                `json:"member_count"`
	Name         string             `json:"name"`
	OwnerId      openapi_types.UUID `json:"owner_id"`
	TournamentId openapi_types.UUID `json:"tournament_id"`
	UpdatedAt    time.Time          `json:"updated_at"`
}

// LeagueListResponse defines model for LeagueListResponse.
type LeagueListResponse struct {
	Leagues []LeagueListItem `json:"leagues"`
}

// LeagueMember defines model for LeagueMember.
type LeagueMember struct {
	JoinedAt time.Time          `json:"joined_at"`
	Role     LeagueMemberRole   `json:"role"`
	UserId   openapi_types.UUID `json:"user_id"`
}

// LeagueMemberRole defines model for LeagueMember.Role.
type LeagueMemberRole string

// LeagueMemberPlayerPick defines model for LeagueMemberPlayerPick.
type LeagueMemberPlayerPick struct {
	DisplayName string              `json:"display_name"`
	PlayerId    *openapi_types.UUID `json:"player_id,omitempty"`
	PlayerName  *string             `json:"player_name,omitempty"`
	Points      *int                `json:"points,omitempty"`
	UserId      openapi_types.UUID  `json:"user_id"`
}

// LeagueMemberScorePrediction defines model for LeagueMemberScorePrediction.
type LeagueMemberScorePrediction struct {
	DisplayName string             `json:"display_name"`
	GoalsAway   *int               `json:"goals_away,omitempty"`
	GoalsHome   *int               `json:"goals_home,omitempty"`
	Points      *int               `json:"points,omitempty"`
	UserId      openapi_types.UUID `json:"user_id"`
}

// LeagueMemberTeamPick defines model for LeagueMemberTeamPick.
type LeagueMemberTeamPick struct {
	DisplayName string              `json:"display_name"`
	Points      *int                `json:"points,omitempty"`
	TeamId      *openapi_types.UUID `json:"team_id,omitempty"`
	TeamName    *string             `json:"team_name,omitempty"`
	UserId      openapi_types.UUID  `json:"user_id"`
}

// LeaguePlayerCategoryView defines model for LeaguePlayerCategoryView.
type LeaguePlayerCategoryView struct {
	Category PlayerHandicapCategory `json:"category"`

	// Group Group letter (e.g. "A"). Present only for group-scoped categories.
	Group       *string                  `json:"group,omitempty"`
	Predictions []LeagueMemberPlayerPick `json:"predictions"`
}

// LeagueTeamCategoryView defines model for LeagueTeamCategoryView.
type LeagueTeamCategoryView struct {
	Category TeamHandicapCategory `json:"category"`

	// Group Group letter (e.g. "A"). Present only for group-scoped categories.
	Group       *string                `json:"group,omitempty"`
	Predictions []LeagueMemberTeamPick `json:"predictions"`
}

// Player defines model for Player.
type Player struct {
	// Group Group letter of the player's team (e.g. "A"), or null if not applicable.
	Group     *string            `json:"group,omitempty"`
	Handicaps map[string]int     `json:"handicaps"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	TeamLogo  string             `json:"team_logo"`
	TeamName  string             `json:"team_name"`
}

// PlayerHandicap defines model for PlayerHandicap.
type PlayerHandicap struct {
	Points int `json:"points"`
}

// PlayerHandicapCategory defines model for PlayerHandicapCategory.
type PlayerHandicapCategory string

// PlayerListResponse defines model for PlayerListResponse.
type PlayerListResponse struct {
	Players []Player `json:"players"`
}

// PlayerPredictionView defines model for PlayerPredictionView.
type PlayerPredictionView struct {
	Category PlayerHandicapCategory `json:"category"`

	// Group Group letter (e.g. "A"). Present only for group-scoped categories.
	Group      *string             `json:"group,omitempty"`
	PlayerId   *openapi_types.UUID `json:"player_id,omitempty"`
	PlayerName *string             `json:"player_name,omitempty"`
	Points     *int                `json:"points,omitempty"`
}

// PlayerPredictionsListResponse defines model for PlayerPredictionsListResponse.
type PlayerPredictionsListResponse struct {
	// Locked Whether predictions are locked (first kickoff is within 30 minutes or has passed).
	Locked      bool                   `json:"locked"`
	Predictions []PlayerPredictionView `json:"predictions"`
}

// ScorePredictionResponse defines model for ScorePredictionResponse.
type ScorePredictionResponse struct {
	FixtureId openapi_types.UUID `json:"fixture_id"`
	GoalsAway int                `json:"goals_away"`
	GoalsHome int                `json:"goals_home"`
	Id        openapi_types.UUID `json:"id"`
	Points    *int               `json:"points,omitempty"`
}

// TeamHandicapCategory defines model for TeamHandicapCategory.
type TeamHandicapCategory string

// TeamHandicapItem defines model for TeamHandicapItem.
type TeamHandicapItem struct {
	Category TeamHandicapCategory `json:"category"`
	Points   int                  `json:"points"`
}

// TeamListResponse defines model for TeamListResponse.
type TeamListResponse struct {
	Teams []TeamWithHandicaps `json:"teams"`
}

// TeamPredictionView defines model for TeamPredictionView.
type TeamPredictionView struct {
	Category TeamHandicapCategory `json:"category"`

	// Group Group letter (e.g. "A"). Present only for group-scoped categories.
	Group    *string             `json:"group,omitempty"`
	Points   *int                `json:"points,omitempty"`
	TeamId   *openapi_types.UUID `json:"team_id,omitempty"`
	TeamName *string             `json:"team_name,omitempty"`
}

// TeamPredictionsListResponse defines model for TeamPredictionsListResponse.
type TeamPredictionsListResponse struct {
	// Locked Whether predictions are locked (first kickoff is within 30 minutes or has passed).
	Locked      bool                 `json:"locked"`
	Predictions []TeamPredictionView `json:"predictions"`
}

// TeamWithHandicaps defines model for TeamWithHandicaps.
type TeamWithHandicaps struct {
	GroupLetter *string            `json:"group_letter,omitempty"`
	Handicaps   []TeamHandicapItem `json:"handicaps"`
	Id          openapi_types.UUID `json:"id"`
	Logo        string             `json:"logo"`
	Name        string             `json:"name"`
}

// Tournament defines model for Tournament.
type Tournament struct {
	CreatedAt time.Time          `json:"created_at"`
	EndsAt    time.Time          `json:"ends_at"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	StartsAt  time.Time          `json:"starts_at"`
	Status    TournamentStatus   `json:"status"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// TournamentStatus defines model for Tournament.Status.
type TournamentStatus string

// TournamentListResponse defines model for TournamentListResponse.
type TournamentListResponse struct {
	Tournaments []Tournament `json:"tournaments"`
}

// UpsertScorePredictionRequest defines model for UpsertScorePredictionRequest.
type UpsertScorePredictionRequest struct {
	GoalsAway int `json:"goals_away"`
	GoalsHome int `json:"goals_home"`
}

// User defines model for User.
type User struct {
	CreatedAt   time.Time           `json:"created_at"`
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	Status      UserStatus          `json:"status"`
	UpdatedAt   time.Time           `json:"updated_at"`
}

// UserStatus defines model for User.Status.
type UserStatus string

// UserFixtureViewResponse defines model for UserFixtureViewResponse.
type UserFixtureViewResponse struct {
	AwayTeamName     string                        `json:"away_team_name"`
	ExternalId       int                           `json:"external_id"`
	GoalsAway        *int                          `json:"goals_away,omitempty"`
	GoalsHome        *int                          `json:"goals_home,omitempty"`
	HomeTeamName     string                        `json:"home_team_name"`
	Id               openapi_types.UUID            `json:"id"`
	KickoffAt        time.Time                     `json:"kickoff_at"`
	Prediction       ScorePredictionResponse       `json:"prediction"`
	PredictionLocked bool                          `json:"prediction_locked"`
	Round            string                        `json:"round"`
	Status           UserFixtureViewResponseStatus `json:"status"`
	TournamentId     openapi_types.UUID            `json:"tournament_id"`
}

// UserFixtureViewResponseStatus defines model for UserFixtureViewResponse.Status.
type UserFixtureViewResponseStatus string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// CreateLeagueJSONBody defines parameters for CreateLeague.
type CreateLeagueJSONBody struct {
	Name         string             `json:"name"`
	TournamentId openapi_types.UUID `json:"tournament_id"`
}

// JoinLeagueJSONBody defines parameters for JoinLeague.
type JoinLeagueJSONBody struct {
	Code string `json:"code"`
}

// UpdateLeagueNameJSONBody defines parameters for UpdateLeagueName.
type UpdateLeagueNameJSONBody struct {
	Name string `json:"name"`
}

// CreateTournamentJSONBody defines parameters for CreateTournament.
type CreateTournamentJSONBody struct {
	EndsAt   time.Time `json:"ends_at"`
	Name     string    `json:"name"`
	Slug     string    `json:"slug"`
	StartsAt time.Time `json:"starts_at"`
}

// SearchPlayersParams defines parameters for SearchPlayers.
type SearchPlayersParams struct {
	Q *string `form:"q,omitempty" json:"q,omitempty"`

	// Group Filter results to players whose team is in this group (e.g. "A"). Omit to search all groups.
	Group *string `form:"group,omitempty" json:"group,omitempty"`

	// HasHandicap When true, only return players that have at least one handicap row.
	HasHandicap *bool `form:"hasHandicap,omitempty" json:"hasHandicap,omitempty"`
}

// CreateLeagueJSONRequestBody defines body for CreateLeague for application/json ContentType.
type CreateLeagueJSONRequestBody CreateLeagueJSONBody

// JoinLeagueJSONRequestBody defines body for JoinLeague for application/json ContentType.
type JoinLeagueJSONRequestBody JoinLeagueJSONBody

// UpdateLeagueNameJSONRequestBody defines body for UpdateLeagueName for application/json ContentType.
type UpdateLeagueNameJSONRequestBody UpdateLeagueNameJSONBody

// UpsertScorePredictionJSONRequestBody defines body for UpsertScorePrediction for application/json ContentType.
type UpsertScorePredictionJSONRequestBody = UpsertScorePredictionRequest

// CreateTournamentJSONRequestBody defines body for CreateTournament for application/json ContentType.
type CreateTournamentJSONRequestBody CreateTournamentJSONBody

// BulkUpsertPlayerPredictionsJSONRequestBody defines body for BulkUpsertPlayerPredictions for application/json ContentType.
type BulkUpsertPlayerPredictionsJSONRequestBody = BulkUpsertPlayerPredictionsRequest

// BulkUpsertTeamPredictionsJSONRequestBody defines body for BulkUpsertTeamPredictions for application/json ContentType.
type BulkUpsertTeamPredictionsJSONRequestBody = BulkUpsertTeamPredictionsRequest
