// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_analysis.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getFixtureAnalysisInput = `-- name: GetFixtureAnalysisInput :one
SELECT
    home_t.name              AS home_team_name,
    away_t.name              AS away_team_name,
    f.round,
    home_t.group_letter,
    f.goals_home,
    f.goals_away,
    coalesce(
        json_agg(json_build_object(
            'display_name', u.display_name,
            'goals_home',   sp.goals_home,
            'goals_away',   sp.goals_away,
            'points',       sp.points
        )) FILTER (WHERE u.id IS NOT NULL),
        '[]'::json
    )::text AS predictions
FROM fixtures f
JOIN teams home_t ON home_t.id = f.home_team_id
JOIN teams away_t ON away_t.id = f.away_team_id
JOIN leagues l ON l.tournament_id = f.tournament_id AND l.id = $1
JOIN league_members lm ON lm.league_id = l.id
JOIN users u ON u.id = lm.user_id
LEFT JOIN score_predictions sp ON sp.fixture_id = f.id AND sp.user_id = lm.user_id
WHERE f.id = $2
GROUP BY f.id, f.round, f.goals_home, f.goals_away, home_t.name, away_t.name, home_t.group_letter
`

type GetFixtureAnalysisInputParams struct {
	LeagueID  uuid.UUID
	FixtureID uuid.UUID
}

type GetFixtureAnalysisInputRow struct {
	HomeTeamName string
	AwayTeamName string
	Round        string
	GroupLetter  *string
	GoalsHome    *int32
	GoalsAway    *int32
	Predictions  string
}

func (q *Queries) GetFixtureAnalysisInput(ctx context.Context, arg GetFixtureAnalysisInputParams) (GetFixtureAnalysisInputRow, error) {
	row := q.db.QueryRow(ctx, getFixtureAnalysisInput, arg.LeagueID, arg.FixtureID)
	var i GetFixtureAnalysisInputRow
	err := row.Scan(
		&i.HomeTeamName,
		&i.AwayTeamName,
		&i.Round,
		&i.GroupLetter,
		&i.GoalsHome,
		&i.GoalsAway,
		&i.Predictions,
	)
	return i, err
}

const listLeaguesForFixture = `-- name: ListLeaguesForFixture :many
SELECT l.id
FROM leagues l
JOIN fixtures f ON f.tournament_id = l.tournament_id
WHERE f.id = $1
`

func (q *Queries) ListLeaguesForFixture(ctx context.Context, fixtureID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listLeaguesForFixture, fixtureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFixtureAnalysis = `-- name: UpsertFixtureAnalysis :exec
INSERT INTO score_ai_analysis (fixture_id, league_id, analysis)
VALUES ($1, $2, $3)
ON CONFLICT (fixture_id, league_id) DO UPDATE SET
    analysis   = EXCLUDED.analysis,
    updated_at = now()
`

type UpsertFixtureAnalysisParams struct {
	FixtureID uuid.UUID
	LeagueID  uuid.UUID
	Analysis  string
}

func (q *Queries) UpsertFixtureAnalysis(ctx context.Context, arg UpsertFixtureAnalysisParams) error {
	_, err := q.db.Exec(ctx, upsertFixtureAnalysis, arg.FixtureID, arg.LeagueID, arg.Analysis)
	return err
}
