// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fixtures.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getFirstKickoffByTournament = `-- name: GetFirstKickoffByTournament :one
SELECT kickoff_at
FROM fixtures
WHERE tournament_id = $1
ORDER BY kickoff_at ASC
LIMIT 1
`

func (q *Queries) GetFirstKickoffByTournament(ctx context.Context, tournamentID uuid.UUID) (time.Time, error) {
	row := q.db.QueryRow(ctx, getFirstKickoffByTournament, tournamentID)
	var kickoff_at time.Time
	err := row.Scan(&kickoff_at)
	return kickoff_at, err
}
