// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fixtures.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getFixtureByID = `-- name: GetFixtureByID :one
SELECT id, external_id, tournament_id, home_team_id, away_team_id,
       kickoff_at, status, goals_home, goals_away, created_at, updated_at
FROM fixtures
WHERE id = $1
`

func (q *Queries) GetFixtureByID(ctx context.Context, id uuid.UUID) (Fixture, error) {
	row := q.db.QueryRow(ctx, getFixtureByID, id)
	var i Fixture
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.TournamentID,
		&i.HomeTeamID,
		&i.AwayTeamID,
		&i.KickoffAt,
		&i.Status,
		&i.GoalsHome,
		&i.GoalsAway,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFixturesByTournament = `-- name: ListFixturesByTournament :many
SELECT id, external_id, tournament_id, home_team_id, away_team_id,
       kickoff_at, status, goals_home, goals_away, created_at, updated_at
FROM fixtures
WHERE tournament_id = $1
ORDER BY kickoff_at
`

func (q *Queries) ListFixturesByTournament(ctx context.Context, tournamentID uuid.UUID) ([]Fixture, error) {
	rows, err := q.db.Query(ctx, listFixturesByTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fixture{}
	for rows.Next() {
		var i Fixture
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.TournamentID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.KickoffAt,
			&i.Status,
			&i.GoalsHome,
			&i.GoalsAway,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLockedFixturesByLeague = `-- name: ListLockedFixturesByLeague :many
SELECT f.id, f.external_id, f.tournament_id, f.home_team_id, f.away_team_id,
       f.kickoff_at, f.status, f.goals_home, f.goals_away, f.created_at, f.updated_at,
       coalesce(
           json_agg(
               json_build_object(
                   'user_id',     lm.user_id,
                   'display_name', u.display_name,
                   'goals_home',  sp.goals_home,
                   'goals_away',  sp.goals_away,
                   'points',      sp.points
               ) ORDER BY (lm.user_id = $1) DESC, u.display_name ASC
           ),
           '[]'::json
       ) AS member_predictions
FROM fixtures f
JOIN leagues l ON l.tournament_id = f.tournament_id
JOIN league_members lm ON lm.league_id = l.id
JOIN users u ON u.id = lm.user_id
LEFT JOIN score_predictions sp
    ON sp.fixture_id = f.id AND sp.user_id = lm.user_id
WHERE l.id = $2
  AND f.status IN ('in_progress', 'finished')
GROUP BY f.id
ORDER BY f.kickoff_at DESC
`

type ListLockedFixturesByLeagueParams struct {
	RequestingUserID uuid.UUID
	LeagueID         uuid.UUID
}

type ListLockedFixturesByLeagueRow struct {
	ID                uuid.UUID
	ExternalID        int64
	TournamentID      uuid.UUID
	HomeTeamID        uuid.UUID
	AwayTeamID        uuid.UUID
	KickoffAt         time.Time
	Status            FixtureStatus
	GoalsHome         *int32
	GoalsAway         *int32
	CreatedAt         time.Time
	UpdatedAt         time.Time
	MemberPredictions interface{}
}

func (q *Queries) ListLockedFixturesByLeague(ctx context.Context, arg ListLockedFixturesByLeagueParams) ([]ListLockedFixturesByLeagueRow, error) {
	rows, err := q.db.Query(ctx, listLockedFixturesByLeague, arg.RequestingUserID, arg.LeagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLockedFixturesByLeagueRow{}
	for rows.Next() {
		var i ListLockedFixturesByLeagueRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.TournamentID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.KickoffAt,
			&i.Status,
			&i.GoalsHome,
			&i.GoalsAway,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MemberPredictions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
