// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: league.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const addLeagueMember = `-- name: AddLeagueMember :one
INSERT INTO league_members (league_id, user_id, role)
VALUES ($1, $2, $3)
RETURNING league_id, user_id, role, joined_at
`

type AddLeagueMemberParams struct {
	LeagueID uuid.UUID
	UserID   uuid.UUID
	Role     LeagueMemberRole
}

func (q *Queries) AddLeagueMember(ctx context.Context, arg AddLeagueMemberParams) (LeagueMember, error) {
	row := q.db.QueryRow(ctx, addLeagueMember, arg.LeagueID, arg.UserID, arg.Role)
	var i LeagueMember
	err := row.Scan(
		&i.LeagueID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const createLeague = `-- name: CreateLeague :one
INSERT INTO leagues (id, tournament_id, owner_id, name, code)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tournament_id, owner_id, name, code, created_at, updated_at
`

type CreateLeagueParams struct {
	ID           uuid.UUID
	TournamentID uuid.UUID
	OwnerID      uuid.UUID
	Name         string
	Code         string
}

func (q *Queries) CreateLeague(ctx context.Context, arg CreateLeagueParams) (League, error) {
	row := q.db.QueryRow(ctx, createLeague,
		arg.ID,
		arg.TournamentID,
		arg.OwnerID,
		arg.Name,
		arg.Code,
	)
	var i League
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OwnerID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLeague = `-- name: DeleteLeague :exec
DELETE FROM leagues
WHERE id = $1
`

func (q *Queries) DeleteLeague(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLeague, id)
	return err
}

const getLeagueByCode = `-- name: GetLeagueByCode :one
SELECT id, tournament_id, owner_id, name, code, created_at, updated_at
FROM leagues
WHERE code = $1
`

func (q *Queries) GetLeagueByCode(ctx context.Context, code string) (League, error) {
	row := q.db.QueryRow(ctx, getLeagueByCode, code)
	var i League
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OwnerID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeagueByID = `-- name: GetLeagueByID :one
SELECT id, tournament_id, owner_id, name, code, created_at, updated_at
FROM leagues
WHERE id = $1
`

func (q *Queries) GetLeagueByID(ctx context.Context, id uuid.UUID) (League, error) {
	row := q.db.QueryRow(ctx, getLeagueByID, id)
	var i League
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OwnerID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLeagueMember = `-- name: GetLeagueMember :one
SELECT league_id, user_id, role, joined_at
FROM league_members
WHERE league_id = $1 AND user_id = $2
`

type GetLeagueMemberParams struct {
	LeagueID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) GetLeagueMember(ctx context.Context, arg GetLeagueMemberParams) (LeagueMember, error) {
	row := q.db.QueryRow(ctx, getLeagueMember, arg.LeagueID, arg.UserID)
	var i LeagueMember
	err := row.Scan(
		&i.LeagueID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const listLeagueMembersForLeague = `-- name: ListLeagueMembersForLeague :many
SELECT league_id, user_id, role, joined_at
FROM league_members
WHERE league_id = $1
ORDER BY joined_at ASC
`

func (q *Queries) ListLeagueMembersForLeague(ctx context.Context, leagueID uuid.UUID) ([]LeagueMember, error) {
	rows, err := q.db.Query(ctx, listLeagueMembersForLeague, leagueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeagueMember{}
	for rows.Next() {
		var i LeagueMember
		if err := rows.Scan(
			&i.LeagueID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeaguesForUser = `-- name: ListLeaguesForUser :many
SELECT l.id, l.tournament_id, l.owner_id, l.name, l.code, l.created_at, l.updated_at
FROM leagues l
JOIN league_members lm ON lm.league_id = l.id
WHERE lm.user_id = $1
ORDER BY l.created_at DESC
`

func (q *Queries) ListLeaguesForUser(ctx context.Context, userID uuid.UUID) ([]League, error) {
	rows, err := q.db.Query(ctx, listLeaguesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []League{}
	for rows.Next() {
		var i League
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.OwnerID,
			&i.Name,
			&i.Code,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeLeagueMember = `-- name: RemoveLeagueMember :execresult
DELETE FROM league_members
WHERE league_id = $1 AND user_id = $2
`

type RemoveLeagueMemberParams struct {
	LeagueID uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) RemoveLeagueMember(ctx context.Context, arg RemoveLeagueMemberParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, removeLeagueMember, arg.LeagueID, arg.UserID)
}

const updateLeagueCode = `-- name: UpdateLeagueCode :one
UPDATE leagues
SET code = $2
WHERE id = $1
RETURNING id, tournament_id, owner_id, name, code, created_at, updated_at
`

type UpdateLeagueCodeParams struct {
	ID   uuid.UUID
	Code string
}

func (q *Queries) UpdateLeagueCode(ctx context.Context, arg UpdateLeagueCodeParams) (League, error) {
	row := q.db.QueryRow(ctx, updateLeagueCode, arg.ID, arg.Code)
	var i League
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OwnerID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLeagueName = `-- name: UpdateLeagueName :one
UPDATE leagues
SET name = $2
WHERE id = $1
RETURNING id, tournament_id, owner_id, name, code, created_at, updated_at
`

type UpdateLeagueNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateLeagueName(ctx context.Context, arg UpdateLeagueNameParams) (League, error) {
	row := q.db.QueryRow(ctx, updateLeagueName, arg.ID, arg.Name)
	var i League
	err := row.Scan(
		&i.ID,
		&i.TournamentID,
		&i.OwnerID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
