// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type TournamentStatus string

const (
	TournamentStatusUpcoming   TournamentStatus = "upcoming"
	TournamentStatusInProgress TournamentStatus = "in_progress"
	TournamentStatusConcluded  TournamentStatus = "concluded"
)

func (e *TournamentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TournamentStatus(s)
	case string:
		*e = TournamentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TournamentStatus: %T", src)
	}
	return nil
}

type NullTournamentStatus struct {
	TournamentStatus TournamentStatus
	Valid            bool // Valid is true if TournamentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTournamentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TournamentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TournamentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTournamentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TournamentStatus), nil
}

func (e TournamentStatus) Valid() bool {
	switch e {
	case TournamentStatusUpcoming,
		TournamentStatusInProgress,
		TournamentStatusConcluded:
		return true
	}
	return false
}

func AllTournamentStatusValues() []TournamentStatus {
	return []TournamentStatus{
		TournamentStatusUpcoming,
		TournamentStatusInProgress,
		TournamentStatusConcluded,
	}
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

func (e UserStatus) Valid() bool {
	switch e {
	case UserStatusActive,
		UserStatusSuspended:
		return true
	}
	return false
}

func AllUserStatusValues() []UserStatus {
	return []UserStatus{
		UserStatusActive,
		UserStatusSuspended,
	}
}

type Tournament struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	Status    TournamentStatus
	StartsAt  time.Time
	EndsAt    time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID          uuid.UUID
	CognitoSub  string
	Email       string
	DisplayName string
	Status      UserStatus
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
