// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outcomes.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listPlayerOutcomesByTournament = `-- name: ListPlayerOutcomesByTournament :many
SELECT po.id, po.tournament_id, po.category, po.recorded_at,
       p.id AS player_id, p.name AS player_name,
       t.id AS team_id, t.name AS team_name
FROM player_outcomes po
JOIN players p ON p.id = po.player_id
JOIN teams   t ON t.id = p.team_id
WHERE po.tournament_id = $1
ORDER BY po.category ASC, p.name ASC
`

type ListPlayerOutcomesByTournamentRow struct {
	ID           uuid.UUID
	TournamentID uuid.UUID
	Category     PlayerHandicapCategory
	RecordedAt   time.Time
	PlayerID     uuid.UUID
	PlayerName   string
	TeamID       uuid.UUID
	TeamName     string
}

func (q *Queries) ListPlayerOutcomesByTournament(ctx context.Context, tournamentID uuid.UUID) ([]ListPlayerOutcomesByTournamentRow, error) {
	rows, err := q.db.Query(ctx, listPlayerOutcomesByTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlayerOutcomesByTournamentRow{}
	for rows.Next() {
		var i ListPlayerOutcomesByTournamentRow
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.Category,
			&i.RecordedAt,
			&i.PlayerID,
			&i.PlayerName,
			&i.TeamID,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamOutcomesByTournament = `-- name: ListTeamOutcomesByTournament :many
SELECT to_.id, to_.tournament_id, to_.category, to_.recorded_at,
       t.id AS team_id, t.name AS team_name
FROM team_outcomes to_
JOIN teams t ON t.id = to_.team_id
WHERE to_.tournament_id = $1
ORDER BY to_.category ASC, t.name ASC
`

type ListTeamOutcomesByTournamentRow struct {
	ID           uuid.UUID
	TournamentID uuid.UUID
	Category     TeamHandicapCategory
	RecordedAt   time.Time
	TeamID       uuid.UUID
	TeamName     string
}

func (q *Queries) ListTeamOutcomesByTournament(ctx context.Context, tournamentID uuid.UUID) ([]ListTeamOutcomesByTournamentRow, error) {
	rows, err := q.db.Query(ctx, listTeamOutcomesByTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamOutcomesByTournamentRow{}
	for rows.Next() {
		var i ListTeamOutcomesByTournamentRow
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.Category,
			&i.RecordedAt,
			&i.TeamID,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
