// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player_handicap_defaults.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getPlayerHandicapDefaults = `-- name: GetPlayerHandicapDefaults :many
SELECT category, default_points
FROM player_handicap_defaults
WHERE tournament_id = $1
`

type GetPlayerHandicapDefaultsRow struct {
	Category      PlayerHandicapCategory
	DefaultPoints int32
}

func (q *Queries) GetPlayerHandicapDefaults(ctx context.Context, tournamentID uuid.UUID) ([]GetPlayerHandicapDefaultsRow, error) {
	rows, err := q.db.Query(ctx, getPlayerHandicapDefaults, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPlayerHandicapDefaultsRow{}
	for rows.Next() {
		var i GetPlayerHandicapDefaultsRow
		if err := rows.Scan(&i.Category, &i.DefaultPoints); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
