// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT id, external_id, name, tournament_id, team_id, created_at, updated_at
FROM players
WHERE id = $1
`

func (q *Queries) GetPlayerByID(ctx context.Context, id uuid.UUID) (Player, error) {
	row := q.db.QueryRow(ctx, getPlayerByID, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.TournamentID,
		&i.TeamID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchPlayers = `-- name: SearchPlayers :many
WITH top_players AS (
    SELECT p.id, p.name, t.name AS team_name, t.logo AS team_logo, p.tournament_id
    FROM players p
    JOIN teams t ON t.id = p.team_id
    WHERE p.tournament_id = $2
      AND unaccent_immutable(p.name) ILIKE '%' || unaccent_immutable($3) || '%' ESCAPE '\'
    ORDER BY similarity(unaccent_immutable(p.name), unaccent_immutable($1)) DESC
    LIMIT 5
)
SELECT tp.id, tp.name, tp.team_name, tp.team_logo, tp.tournament_id,
       coalesce(
           json_object_agg(ph.category, ph.points) FILTER (WHERE ph.category IS NOT NULL),
           '{}'::json
       )::text AS handicaps
FROM top_players tp
LEFT JOIN player_handicap ph ON ph.player_id = tp.id
GROUP BY tp.id, tp.name, tp.team_name, tp.team_logo, tp.tournament_id
ORDER BY similarity(unaccent_immutable(tp.name), unaccent_immutable($1)) DESC
`

type SearchPlayersParams struct {
	RawQuery     string
	TournamentID uuid.UUID
	EscapedQuery string
}

type SearchPlayersRow struct {
	ID           uuid.UUID
	Name         string
	TeamName     string
	TeamLogo     string
	TournamentID uuid.UUID
	Handicaps    string
}

// @escaped_query: wildcard-escaped term for ILIKE filtering
// @raw_query:     original trimmed term for similarity ranking (must not be escaped)
func (q *Queries) SearchPlayers(ctx context.Context, arg SearchPlayersParams) ([]SearchPlayersRow, error) {
	rows, err := q.db.Query(ctx, searchPlayers, arg.RawQuery, arg.TournamentID, arg.EscapedQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlayersRow{}
	for rows.Next() {
		var i SearchPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeamName,
			&i.TeamLogo,
			&i.TournamentID,
			&i.Handicaps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
