// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player_handicap.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getPlayerHandicap = `-- name: GetPlayerHandicap :one
SELECT id, player_id, category, points
FROM player_handicap
WHERE player_id = $1
  AND category  = $2
`

type GetPlayerHandicapParams struct {
	PlayerID uuid.UUID
	Category PlayerHandicapCategory
}

func (q *Queries) GetPlayerHandicap(ctx context.Context, arg GetPlayerHandicapParams) (PlayerHandicap, error) {
	row := q.db.QueryRow(ctx, getPlayerHandicap, arg.PlayerID, arg.Category)
	var i PlayerHandicap
	err := row.Scan(
		&i.ID,
		&i.PlayerID,
		&i.Category,
		&i.Points,
	)
	return i, err
}
