// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const searchPlayers = `-- name: SearchPlayers :many
SELECT p.id, p.name, t.name AS team_name, t.logo AS team_logo, p.tournament_id
FROM players p
JOIN teams t ON t.id = p.team_id
WHERE p.tournament_id = $1
  AND unaccent_immutable(p.name) ILIKE '%' || unaccent_immutable($2) || '%' ESCAPE '\'
ORDER BY similarity(unaccent_immutable(p.name), unaccent_immutable($3)) DESC
LIMIT 5
`

type SearchPlayersParams struct {
	TournamentID uuid.UUID
	EscapedQuery string
	RawQuery     string
}

type SearchPlayersRow struct {
	ID           uuid.UUID
	Name         string
	TeamName     string
	TeamLogo     string
	TournamentID uuid.UUID
}

// @escaped_query: wildcard-escaped term for ILIKE filtering
// @raw_query:     original trimmed term for similarity ranking (must not be escaped)
func (q *Queries) SearchPlayers(ctx context.Context, arg SearchPlayersParams) ([]SearchPlayersRow, error) {
	rows, err := q.db.Query(ctx, searchPlayers, arg.TournamentID, arg.EscapedQuery, arg.RawQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlayersRow{}
	for rows.Next() {
		var i SearchPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeamName,
			&i.TeamLogo,
			&i.TournamentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
