// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: player.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getPlayerByID = `-- name: GetPlayerByID :one
SELECT p.id, p.external_id, p.name, p.tournament_id, p.team_id,
       t.group_letter,
       p.created_at, p.updated_at
FROM players p
JOIN teams t ON t.id = p.team_id
WHERE p.id = $1
`

type GetPlayerByIDRow struct {
	ID           uuid.UUID
	ExternalID   int64
	Name         string
	TournamentID uuid.UUID
	TeamID       uuid.UUID
	GroupLetter  *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) GetPlayerByID(ctx context.Context, id uuid.UUID) (GetPlayerByIDRow, error) {
	row := q.db.QueryRow(ctx, getPlayerByID, id)
	var i GetPlayerByIDRow
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Name,
		&i.TournamentID,
		&i.TeamID,
		&i.GroupLetter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchPlayers = `-- name: SearchPlayers :many
WITH top_players AS (
    SELECT p.id, p.name, t.name AS team_name, t.logo AS team_logo, t.group_letter, p.tournament_id
    FROM players p
    JOIN teams t ON t.id = p.team_id
    WHERE p.tournament_id = $4
      AND ($5 = '' OR t.group_letter = $5)
      AND ($2 = '' OR unaccent_immutable(p.name) ILIKE '%' || unaccent_immutable($2) || '%' ESCAPE '\')
    ORDER BY CASE WHEN $2 = '' THEN p.name ELSE NULL END,
             CASE WHEN $2 <> '' THEN similarity(unaccent_immutable(p.name), unaccent_immutable($3)) ELSE NULL END DESC
)
SELECT tp.id, tp.name, tp.team_name, tp.team_logo, tp.group_letter, tp.tournament_id,
       coalesce(
           json_object_agg(ph.category, ph.points) FILTER (WHERE ph.category IS NOT NULL),
           '{}'::json
       )::text AS handicaps
FROM top_players tp
LEFT JOIN player_handicap ph ON ph.player_id = tp.id
GROUP BY tp.id, tp.name, tp.team_name, tp.team_logo, tp.group_letter, tp.tournament_id
HAVING NOT $1 OR count(ph.player_id) > 0
ORDER BY CASE WHEN $2 = '' THEN tp.name ELSE NULL END,
         CASE WHEN $2 <> '' THEN similarity(unaccent_immutable(tp.name), unaccent_immutable($3)) ELSE NULL END DESC
`

type SearchPlayersParams struct {
	HasHandicap  interface{}
	EscapedQuery interface{}
	RawQuery     string
	TournamentID uuid.UUID
	GroupLetter  interface{}
}

type SearchPlayersRow struct {
	ID           uuid.UUID
	Name         string
	TeamName     string
	TeamLogo     string
	GroupLetter  *string
	TournamentID uuid.UUID
	Handicaps    string
}

// @escaped_query: wildcard-escaped term for ILIKE filtering; empty string skips name filter
// @raw_query:     original trimmed term for similarity ranking (must not be escaped)
// @group_letter:  optional group filter; empty string means search all groups
// @has_handicap:  when true, only return players with at least one handicap row
func (q *Queries) SearchPlayers(ctx context.Context, arg SearchPlayersParams) ([]SearchPlayersRow, error) {
	rows, err := q.db.Query(ctx, searchPlayers,
		arg.HasHandicap,
		arg.EscapedQuery,
		arg.RawQuery,
		arg.TournamentID,
		arg.GroupLetter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPlayersRow{}
	for rows.Next() {
		var i SearchPlayersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeamName,
			&i.TeamLogo,
			&i.GroupLetter,
			&i.TournamentID,
			&i.Handicaps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
