// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, logo, tournament_id, group_letter
FROM teams
WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Logo,
		&i.TournamentID,
		&i.GroupLetter,
	)
	return i, err
}

const listGroupLettersByTournament = `-- name: ListGroupLettersByTournament :many
SELECT DISTINCT group_letter
FROM teams
WHERE tournament_id = $1
  AND group_letter IS NOT NULL
ORDER BY group_letter ASC
`

func (q *Queries) ListGroupLettersByTournament(ctx context.Context, tournamentID uuid.UUID) ([]*string, error) {
	rows, err := q.db.Query(ctx, listGroupLettersByTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var group_letter *string
		if err := rows.Scan(&group_letter); err != nil {
			return nil, err
		}
		items = append(items, group_letter)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
