// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, logo, tournament_id
FROM teams
WHERE id = $1
`

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Logo,
		&i.TournamentID,
	)
	return i, err
}
