// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team_handicap.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getTeamHandicap = `-- name: GetTeamHandicap :one
SELECT id, team_id, category, points
FROM team_handicap
WHERE team_id  = $1
  AND category = $2
`

type GetTeamHandicapParams struct {
	TeamID   uuid.UUID
	Category TeamHandicapCategory
}

func (q *Queries) GetTeamHandicap(ctx context.Context, arg GetTeamHandicapParams) (TeamHandicap, error) {
	row := q.db.QueryRow(ctx, getTeamHandicap, arg.TeamID, arg.Category)
	var i TeamHandicap
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Category,
		&i.Points,
	)
	return i, err
}
