// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, short_name, logo, tournament_id, group_letter
FROM teams
WHERE id = $1
`

type GetTeamByIDRow struct {
	ID           uuid.UUID
	Name         string
	ShortName    string
	Logo         string
	TournamentID uuid.UUID
	GroupLetter  *string
}

func (q *Queries) GetTeamByID(ctx context.Context, id uuid.UUID) (GetTeamByIDRow, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i GetTeamByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ShortName,
		&i.Logo,
		&i.TournamentID,
		&i.GroupLetter,
	)
	return i, err
}

const listGroupLettersByTournament = `-- name: ListGroupLettersByTournament :many
SELECT DISTINCT group_letter
FROM teams
WHERE tournament_id = $1
  AND group_letter IS NOT NULL
ORDER BY group_letter ASC
`

func (q *Queries) ListGroupLettersByTournament(ctx context.Context, tournamentID uuid.UUID) ([]*string, error) {
	rows, err := q.db.Query(ctx, listGroupLettersByTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var group_letter *string
		if err := rows.Scan(&group_letter); err != nil {
			return nil, err
		}
		items = append(items, group_letter)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamsWithHandicapsByTournament = `-- name: ListTeamsWithHandicapsByTournament :many
SELECT
    t.id,
    t.name,
    t.short_name,
    t.logo,
    t.tournament_id,
    t.group_letter,
    th.category AS handicap_category,
    th.points   AS handicap_points
FROM teams t
LEFT JOIN team_handicap th ON th.team_id = t.id
WHERE t.tournament_id = $1
ORDER BY t.name ASC, th.category ASC
`

type ListTeamsWithHandicapsByTournamentRow struct {
	ID               uuid.UUID
	Name             string
	ShortName        string
	Logo             string
	TournamentID     uuid.UUID
	GroupLetter      *string
	HandicapCategory *TeamHandicapCategory
	HandicapPoints   *int32
}

func (q *Queries) ListTeamsWithHandicapsByTournament(ctx context.Context, tournamentID uuid.UUID) ([]ListTeamsWithHandicapsByTournamentRow, error) {
	rows, err := q.db.Query(ctx, listTeamsWithHandicapsByTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamsWithHandicapsByTournamentRow{}
	for rows.Next() {
		var i ListTeamsWithHandicapsByTournamentRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ShortName,
			&i.Logo,
			&i.TournamentID,
			&i.GroupLetter,
			&i.HandicapCategory,
			&i.HandicapPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
