// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tournament.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTournament = `-- name: CreateTournament :one
INSERT INTO tournaments (id, slug, name, starts_at, ends_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, slug, name, status, starts_at, ends_at, created_at, updated_at
`

type CreateTournamentParams struct {
	ID       uuid.UUID
	Slug     string
	Name     string
	StartsAt time.Time
	EndsAt   time.Time
}

func (q *Queries) CreateTournament(ctx context.Context, arg CreateTournamentParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, createTournament,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTournamentByID = `-- name: GetTournamentByID :one
SELECT id, slug, name, status, starts_at, ends_at, created_at, updated_at
FROM tournaments
WHERE id = $1
`

func (q *Queries) GetTournamentByID(ctx context.Context, id uuid.UUID) (Tournament, error) {
	row := q.db.QueryRow(ctx, getTournamentByID, id)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTournamentBySlug = `-- name: GetTournamentBySlug :one
SELECT id, slug, name, status, starts_at, ends_at, created_at, updated_at
FROM tournaments
WHERE slug = $1
`

func (q *Queries) GetTournamentBySlug(ctx context.Context, slug string) (Tournament, error) {
	row := q.db.QueryRow(ctx, getTournamentBySlug, slug)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTournaments = `-- name: ListTournaments :many
SELECT id, slug, name, status, starts_at, ends_at, created_at, updated_at
FROM tournaments
ORDER BY starts_at DESC
`

func (q *Queries) ListTournaments(ctx context.Context) ([]Tournament, error) {
	rows, err := q.db.Query(ctx, listTournaments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tournament{}
	for rows.Next() {
		var i Tournament
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
