// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tournament_group_table.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listGroupTableByTournament = `-- name: ListGroupTableByTournament :many
SELECT tgt.id, tgt.tournament_id, tgt.team_id, t.name AS team_name,
       tgt.group_letter, tgt.position, tgt.points, tgt.played, tgt.created_at, tgt.updated_at
FROM tournament_group_table tgt
JOIN teams t ON t.id = tgt.team_id
WHERE tgt.tournament_id = $1
ORDER BY tgt.group_letter ASC, tgt.position ASC
`

type ListGroupTableByTournamentRow struct {
	ID           uuid.UUID
	TournamentID uuid.UUID
	TeamID       uuid.UUID
	TeamName     string
	GroupLetter  string
	Position     int16
	Points       int16
	Played       int16
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) ListGroupTableByTournament(ctx context.Context, tournamentID uuid.UUID) ([]ListGroupTableByTournamentRow, error) {
	rows, err := q.db.Query(ctx, listGroupTableByTournament, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupTableByTournamentRow{}
	for rows.Next() {
		var i ListGroupTableByTournamentRow
		if err := rows.Scan(
			&i.ID,
			&i.TournamentID,
			&i.TeamID,
			&i.TeamName,
			&i.GroupLetter,
			&i.Position,
			&i.Points,
			&i.Played,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
