// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByCognitoSub = `-- name: GetUserByCognitoSub :one
SELECT id, cognito_sub, email, display_name, status, created_at, updated_at, timezone, silent_from, silent_until
FROM users
WHERE cognito_sub = $1
`

func (q *Queries) GetUserByCognitoSub(ctx context.Context, cognitoSub string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByCognitoSub, cognitoSub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.SilentFrom,
		&i.SilentUntil,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, cognito_sub, email, display_name, status, created_at, updated_at, timezone, silent_from, silent_until
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.SilentFrom,
		&i.SilentUntil,
	)
	return i, err
}

const updateDisplayName = `-- name: UpdateDisplayName :one
UPDATE users
SET display_name = $2,
    status       = CASE WHEN status = 'pending_profile' THEN 'active'::user_status ELSE status END
WHERE id = $1
RETURNING id, cognito_sub, email, display_name, status, created_at, updated_at, timezone, silent_from, silent_until
`

type UpdateDisplayNameParams struct {
	ID          uuid.UUID
	DisplayName string
}

func (q *Queries) UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.SilentFrom,
		&i.SilentUntil,
	)
	return i, err
}

const updateTimezone = `-- name: UpdateTimezone :one
UPDATE users
SET timezone     = $2,
    silent_from  = $3,
    silent_until = $4,
    updated_at   = now()
WHERE id = $1
RETURNING id, cognito_sub, email, display_name, status, created_at, updated_at, timezone, silent_from, silent_until
`

type UpdateTimezoneParams struct {
	ID          uuid.UUID
	Timezone    string
	SilentFrom  pgtype.Time
	SilentUntil pgtype.Time
}

func (q *Queries) UpdateTimezone(ctx context.Context, arg UpdateTimezoneParams) (User, error) {
	row := q.db.QueryRow(ctx, updateTimezone,
		arg.ID,
		arg.Timezone,
		arg.SilentFrom,
		arg.SilentUntil,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.SilentFrom,
		&i.SilentUntil,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (id, cognito_sub, email, display_name)
VALUES ($1, $2, $3, $4)
ON CONFLICT (cognito_sub) DO UPDATE
    SET email        = EXCLUDED.email,
        display_name = CASE
                           WHEN users.display_name = '' THEN EXCLUDED.display_name
                           ELSE users.display_name
                       END,
        updated_at   = now()
RETURNING id, cognito_sub, email, display_name, status, created_at, updated_at, timezone, silent_from, silent_until
`

type UpsertUserParams struct {
	ID          uuid.UUID
	CognitoSub  string
	Email       string
	DisplayName string
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.CognitoSub,
		arg.Email,
		arg.DisplayName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CognitoSub,
		&i.Email,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Timezone,
		&i.SilentFrom,
		&i.SilentUntil,
	)
	return i, err
}
