// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countIncompleteGroupFixtures = `-- name: CountIncompleteGroupFixtures :one
SELECT COUNT(*)::int AS n
FROM fixtures f
JOIN teams home_t ON home_t.id = f.home_team_id
WHERE f.tournament_id = $1
  AND home_t.group_letter = $2
  AND f.status NOT IN ('finished', 'cancelled')
`

type CountIncompleteGroupFixturesParams struct {
	TournamentID uuid.UUID
	GroupLetter  *string
}

func (q *Queries) CountIncompleteGroupFixtures(ctx context.Context, arg CountIncompleteGroupFixturesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countIncompleteGroupFixtures, arg.TournamentID, arg.GroupLetter)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const countIncompleteGroupStageFixtures = `-- name: CountIncompleteGroupStageFixtures :one
SELECT COUNT(*)::int AS n
FROM fixtures f
JOIN teams home_t ON home_t.id = f.home_team_id
WHERE f.tournament_id = $1
  AND home_t.group_letter IS NOT NULL
  AND f.status NOT IN ('finished', 'cancelled')
`

func (q *Queries) CountIncompleteGroupStageFixtures(ctx context.Context, tournamentID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countIncompleteGroupStageFixtures, tournamentID)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const countIncompleteRoundFixtures = `-- name: CountIncompleteRoundFixtures :one
SELECT COUNT(*)::int AS n
FROM fixtures f
WHERE f.tournament_id = $1
  AND f.round = $2
  AND f.winner_team_id IS NULL
`

type CountIncompleteRoundFixturesParams struct {
	TournamentID uuid.UUID
	Round        string
}

func (q *Queries) CountIncompleteRoundFixtures(ctx context.Context, arg CountIncompleteRoundFixturesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countIncompleteRoundFixtures, arg.TournamentID, arg.Round)
	var n int32
	err := row.Scan(&n)
	return n, err
}

const getPlayerByExternalID = `-- name: GetPlayerByExternalID :one
SELECT id FROM players
WHERE external_id = $1
  AND tournament_id = $2
`

type GetPlayerByExternalIDParams struct {
	ExternalID   int64
	TournamentID uuid.UUID
}

func (q *Queries) GetPlayerByExternalID(ctx context.Context, arg GetPlayerByExternalIDParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getPlayerByExternalID, arg.ExternalID, arg.TournamentID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getTeamByExternalID = `-- name: GetTeamByExternalID :one
SELECT id FROM teams
WHERE external_id = $1
  AND tournament_id = $2
LIMIT 1
`

type GetTeamByExternalIDParams struct {
	ExternalID   *int64
	TournamentID uuid.UUID
}

func (q *Queries) GetTeamByExternalID(ctx context.Context, arg GetTeamByExternalIDParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTeamByExternalID, arg.ExternalID, arg.TournamentID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listPollableMatches = `-- name: ListPollableMatches :many
SELECT f.id, f.external_id, f.tournament_id,
       f.home_team_id, f.away_team_id,
       t.external_id                                                      AS tournament_external_id,
       t.season                                                           AS tournament_season,
       home_t.group_letter,
       f.round, f.status, f.kickoff_at,
       f.goals_home, f.goals_away,
       f.winner_team_id,
       COALESCE(f.last_polled_at, '0001-01-01 00:00:00 UTC'::timestamptz) AS last_polled_at
FROM fixtures f
JOIN tournaments t     ON t.id = f.tournament_id
JOIN teams       home_t ON home_t.id = f.home_team_id
WHERE f.is_demo = FALSE
  AND t.external_id IS NOT NULL
  AND (
    f.status = 'in_progress'
    OR (f.status = 'upcoming'  AND f.kickoff_at <= now() + INTERVAL '5 minutes')
  )
ORDER BY f.kickoff_at ASC
`

type ListPollableMatchesRow struct {
	ID                   uuid.UUID
	ExternalID           int64
	TournamentID         uuid.UUID
	HomeTeamID           uuid.UUID
	AwayTeamID           uuid.UUID
	TournamentExternalID *int64
	TournamentSeason     *int16
	GroupLetter          *string
	Round                string
	Status               FixtureStatus
	KickoffAt            time.Time
	GoalsHome            *int32
	GoalsAway            *int32
	WinnerTeamID         uuid.UUID
	LastPolledAt         pgtype.Timestamptz
}

func (q *Queries) ListPollableMatches(ctx context.Context) ([]ListPollableMatchesRow, error) {
	rows, err := q.db.Query(ctx, listPollableMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPollableMatchesRow{}
	for rows.Next() {
		var i ListPollableMatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.ExternalID,
			&i.TournamentID,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.TournamentExternalID,
			&i.TournamentSeason,
			&i.GroupLetter,
			&i.Round,
			&i.Status,
			&i.KickoffAt,
			&i.GoalsHome,
			&i.GoalsAway,
			&i.WinnerTeamID,
			&i.LastPolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFixtureStatus = `-- name: UpdateFixtureStatus :exec
UPDATE fixtures
SET status     = $1,
    kickoff_at = $2
WHERE id = $3
`

type UpdateFixtureStatusParams struct {
	Status    FixtureStatus
	KickoffAt time.Time
	ID        uuid.UUID
}

func (q *Queries) UpdateFixtureStatus(ctx context.Context, arg UpdateFixtureStatusParams) error {
	_, err := q.db.Exec(ctx, updateFixtureStatus, arg.Status, arg.KickoffAt, arg.ID)
	return err
}
