// Package docs exposes the committed OpenAPI JSON spec for embedding in the binary.
package docs

import _ "embed"

// SpecJSON is the OpenAPI spec embedded from openapi.json (generated by make generate).
//
//go:embed openapi.json
var SpecJSON []byte
